### ISSUE TITLE
Build a frontend for user authentication

### ISSUE THREAD

**Issue by Aliin** [Aliin/fabricator#2]
- [ ] Maybe use react-form js for the forms https://react-form.js.org
- [ ] Create a navbar component
- [ ] Make a signup, forgot password, and login form that fetches from the backend

**Comment by soueuls** [comment]
I am interested to make this happen although I found react-form to be a terrible piece of code (form state should be kept local and not be part of the global state), I would prefer to use formik instead.

**Comment by Aliin** [comment]
Okay great, I was looking for an alternative for react-form. Let's do it! Linda has set up react with routing, so I hope it works for you - if you need any help with setup let me know. So you should be able to just go ahead :)
