### ISSUE TITLE
Integrate with Github

### ISSUE THREAD

**Issue by Aliin** [Aliin/fabricator#4]
- [ ] use and configure github api gem (https://github.com/piotrmurach/github)
- [ ] allow users to connect to their github account
- [ ] somehow connect to the github repo the project is for
- [ ] enable switching workspace project
- [ ] fetch issues
