### ISSUE TITLE
Build issue tracker

### ISSUE THREAD

**Issue by Aliin** [Aliin/fabricator#5]
- [ ] Create an overview of user stories that are broken down into connected github issues and threads that have an optional connected github issue
- [ ] Allow live discussion through websockets (Rails ActionCable) within each thread / issue
- [ ] Very clearly display if a story or thread has a discussion with your mention
- [ ] Allow to create github issues from here
- [ ] show assignees
